name         'camptocamp-dhcp'
version      '0.3.0'
dependency   'puppetlabs/stdlib', '>= 3.2.0 < 5.0.0'
dependency   'puppetlabs/concat', '>= 1.0.0 < 2.0.0'
source       'https://github.com/camptocamp/puppet-dhcp'
author       'Camptocamp'
license      'Apache 2.0'
summary      'Camptocamp DHCP Module'
description  'DHCP Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-dhcp'
