name         'camptocamp-dhcp'
version      '0.2.0'
dependency   'puppetlabs/stdlib', '0.0.1'
dependency   'ripienaar/concat', '0.0.1'
source       'https://github.com/camptocamp/puppet-dhcp'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp DHCP Module'
description  'DHCP Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-dhcp'
